DefaultContentLanguage: en
MetaDataFormat: yaml
buildFuture: true
baseURL: https://www.roxanarobinson.com
enableRobotsTXT: true
googleAnalytics: 'UA-50141097-3'
languageCode: en-us
themesDir: components
theme:
  - theme-library
  - layout_module-books
  - timeline
  - events
  - layout_module-base  
  - seo
  

preserveTaxonomyNames: true
disableAliases: true
blackfriday:
  extensionsmask:
    - noIntraEmphasis
mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes:
      - ''
outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
    - HTML
    - HEADERS
    - REDIR
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
social: 
   facebook: https://www.facebook.com/roxana.robinson
taxonomies:
  tag: tags

imaging:
  resampleFilter: box
  quality: 99
  anchor: smart
