main:  
  - identifier: books
    name: Books
    url: /book/
    weight: 10
  - identifier: writing
    name: Writing
    url: /writing/
    weight: 20
  - identifier: media
    name: Media
    url: /media/
    weight: 30
  - identifier: news
    name: News
    url: /news/
    weight: 50
  - identifier: events
    name: Appearances
    url: /event/
    weight: 60
  - identifier: about-the-author
    name: Bio
    url: /about-the-author/
    weight: 70
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 80
