url: http://www.roxanarobinson.com
sitename: Roxana Robinson
description: "The official website of author Roxana Robinson, president of the Authors Guild"
primary_image: "/assets/img/Robinson2_JoyceRavid_300x400.jpg"
future: true   # This will tell jekyll to not display future posts

categories:
  - event
  - news

#Jekyll Options
# if using more than one Jekyll instance on your local machine
port: 3575
permalink:  pretty

# Dependencies
markdown: kramdown
# pygments: true
#Pages - store all pages in the _pages directory
include: ['_pages']
relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','license.md','Gemfile', 'Gemfile.lock','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules', 'README.md', 'prose.yaml']
sass:
    style: :compressed
    sass_dir: assets/css/_sass

# dev options (true/false)
# if site is in production, 'production: true'
production: true
bust_css_cache: false
timezone: Etc/Zulu
collections:
  landing_pages:
    output: true
    permalink: '/:path/'
  books:
    output: true
    permalink: '/:collection/:path/'
  book_extras:
    output: true
    permalink: '/:collection/:path/'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'books'
    values:
      layout: "book"
      collectionName: "Books"
      author: Roxana Robinson


# options (data)
addthis_id:
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:
bio: "Roxana Robinson is the author of nine books: five novels, including <em>Cost</em>; three collections of short stories; and the biography <em>Georgia O’Keeffe: A Life</em>. Her work has appeared in <em>The New Yorker</em>, <em>The Atlantic</em>, <em>Harper’s Magazine</em>, <em>The New York Times</em>, <em>The Washington Post</em>, <em>BookForum</em>, <em>Best American Short Stories</em>, <em>Tin House</em> and elsewhere. She teaches in the Hunter MFA Program and divides her time between New York, Connecticut, and Maine. She has received fellowships from the NEA and the Guggenheim Foundation and is the President of the Authors’ Guild."
