# jekyll-seo-tag
title: Roxana Robinson
description: "The official website of author Roxana Robinson, president of the Authors Guild"
url: http://www.roxanarobinson.com
author: []
twitter:
  username: budparr
facebook:
  app_id:
  publisher:
  admins:
logo: /assets/img/Robinson2_JoyceRavid_300x400.jpg
sitename: Roxana Robinson
primary_image: "/assets/img/Robinson2_JoyceRavid_300x400.jpg"
future: true   # This will tell jekyll to not display future posts

categories:
  - event
  - news

#Jekyll Options
# if using more than one Jekyll instance on your local machine

permalink:  pretty
version: 3.0.3
exclude: ['readme.md','license.md','Gemfile', 'Gemfile.lock','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules', 'README.md', 'prose.yaml']
sass:
    style: :compressed
    sass_dir: assets/css/_sass

# dev options (true/false)
# if site is in production, 'production: true'
port: 4003
production: true
bust_css_cache: false
timezone: Etc/Zulu
timezone: Etc/Zulu
compress_html:
  ignore:
    envs: [development]
  profile: false
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes




collections:
  landing_pages:
    output: true
    permalink: '/:path/'
  books:
    output: true
    permalink: '/:collection/:path/'
  book-extras:
    output: true
    permalink: '/:collection/:path/'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'books'
    values:
      layout: "book"
      collectionName: "Books"
      author: Roxana Robinson


# options (data)
addthis_id:
bio: "Roxana Robinson is the author of nine books: five novels, including <em>Cost</em>; three collections of short stories; and the biography <em>Georgia O’Keeffe: A Life</em>. Her work has appeared in <em>The New Yorker</em>, <em>The Atlantic</em>, <em>Harper’s Magazine</em>, <em>The New York Times</em>, <em>The Washington Post</em>, <em>BookForum</em>, <em>Best American Short Stories</em>, <em>Tin House</em> and elsewhere. She teaches in the Hunter MFA Program and divides her time between New York, Connecticut, and Maine. She has received fellowships from the NEA and the Guggenheim Foundation and is the President of the Authors’ Guild."
